import {
  BusinessCenter,
  Explore,
  Group,
  OndemandVideoSharp,
} from "@mui/icons-material";
import Image from "next/image";
import HeaderLink from "../components/headerLink";
import ArrowForwardIosRoundedIcon from "@mui/icons-material/ArrowForwardIosRounded";
import Head from "next/head";
import { getProviders, signIn } from "next-auth/react";

const Home = ({ providers }) => {
  console.log("p: ", providers);
  return (
    <div className="space-y-10 relative">
      <Head>
        <title>LinkedIn Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex justify-around items-center py-4">
        <div className="relative w-36 h-10 ">
          <Image
            alt="logo"
            layout="fill"
            objectFit="contain"
            src="https://content.linkedin.com/content/dam/me/business/en-us/amp/brand-site/v2/bg/LI-Logo.svg.original.svg"
          />
        </div>
        <div className="flex items-center sm:divide-x divide-gray-300">
          <div className="hidden sm:flex space-x-8 pr-4">
            <HeaderLink
              avatar={false}
              feed={false}
              Icon={Explore}
              text="Discover"
            />
            <HeaderLink
              avatar={false}
              feed={false}
              Icon={Group}
              text="People"
            />
            <HeaderLink
              avatar={false}
              feed={false}
              Icon={OndemandVideoSharp}
              text="Learning"
            />
            <HeaderLink
              avatar={false}
              feed={false}
              Icon={BusinessCenter}
              text="Jobs"
            />
          </div>
          {Object.values(providers).map((provider) => (
            <div key={provider.name}>
              <div className="pl-4">
                <button
                  className="text-blue-700 font-semibold rounded-full border border-blue-700 px-5 py-1.5 transition-all hover:border-2"
                  onClick={() => signIn(provider.id, { callbackUrl: "/" })}
                >
                  Sign in
                </button>
              </div>
            </div>
          ))}
        </div>
      </header>
      <main className="flex flex-col xl:flex-row items-center max-w-screen-lg mx-auto">
        <div className="space-y-6 xl:space-y-10">
          <h1 className="text-3xl md:text-5xl text-amber-800/80 max-w-xl !leading-snug pl-4 xl:pl-0">
            Welcome to your professional community
          </h1>
          <div className="space-y-4">
            <div className="intent">
              <h2 className="text-xl">Search for a job</h2>
              <ArrowForwardIosRoundedIcon className="text-gray-700" />
            </div>
            <div className="intent">
              <h2 className="text-xl">Find a person you know</h2>
              <ArrowForwardIosRoundedIcon className="text-gray-700" />
            </div>
            <div className="intent">
              <h2 className="text-xl">Learn a new skill</h2>
              <ArrowForwardIosRoundedIcon className="text-gray-700" />
            </div>
          </div>
        </div>
        <div className="relative xl:absolute w-80 h-80 xl:w-[650px] xl:h-[650px] top-14 right-5">
          <Image
            src="https://cdn.jsdelivr.net/gh/kitety/blog_img@master/img/dxf91zhqd2z6b0bwg85ktm5s4.svg"
            alt="image"
            layout="fill"
            priority
          />
        </div>
      </main>
    </div>
  );
};

export default Home;


export async function getServerSideProps(context) {
  const providers = await getProviders();

  return {
    props: {
      providers,
    },
  };
}
